// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_2Lxgwe06gtuAkVSPLUA-2x8n57ssIU',
    appId: '1:209175269517:web:cf9526c8e49e4a466ed2c4',
    messagingSenderId: '209175269517',
    projectId: 'task-management-67f65',
    authDomain: 'task-management-67f65.firebaseapp.com',
    storageBucket: 'task-management-67f65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvpFpqbJY3pOxYiGoz8tPwTncr3jnt44',
    appId: '1:209175269517:android:5947af613c23ebbe6ed2c4',
    messagingSenderId: '209175269517',
    projectId: 'task-management-67f65',
    storageBucket: 'task-management-67f65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEyqEqswq6PRpgkUDYs9JzkuVaTGjr3Uw',
    appId: '1:209175269517:ios:5450a2efc3550bb06ed2c4',
    messagingSenderId: '209175269517',
    projectId: 'task-management-67f65',
    storageBucket: 'task-management-67f65.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEyqEqswq6PRpgkUDYs9JzkuVaTGjr3Uw',
    appId: '1:209175269517:ios:5450a2efc3550bb06ed2c4',
    messagingSenderId: '209175269517',
    projectId: 'task-management-67f65',
    storageBucket: 'task-management-67f65.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT_2Lxgwe06gtuAkVSPLUA-2x8n57ssIU',
    appId: '1:209175269517:web:55cc4715244d89cd6ed2c4',
    messagingSenderId: '209175269517',
    projectId: 'task-management-67f65',
    authDomain: 'task-management-67f65.firebaseapp.com',
    storageBucket: 'task-management-67f65.appspot.com',
  );

}